### ISSUE TITLE
Can't detect a beacon on Android 

### ISSUE THREAD

**Issue by julianlecalvez** [ezeeworld/B4S-Android-SDK#2]
Hello, 

I'm trying to setup the SDK for android in order to detect one beacon to send a push notification. 

I synchronized my beacon and created a campaign (simple push, from 0 to 1 meter, everyday). 
I set up the android sdk and I deployed it on my nexus 5. 
Everything seems to work well but when I move my beacon by the phone, it never detects or print or send anything. 
What am I suppose to expect ? What did I miss ?

Thanks a lot :) 

Julian

**Comment by eric-kok-ezeeworld** [comment]
Hi Julian. There are several reasons why the SDK does not display any campaign yet, but it should be easy to tell from the logs that the SDK produces. Bluetooth can be disabled, you might not be in a beacon area, the campaign is not valid at this time, etc. 

If you log your android device using:
```adb logcat -s B4S:*``` 
and enable SDK loggin in your app (typically the Application object) using:
```
settings.setShouldLogDebug(true);
settings.setShouldLogVerbose(true);
```
you should see verbose output of the SDK behaviour, such as setting up geofences and beacons that are scanned around you. If there are no geofences around you you might also use developer/demo mode of the SDK, which is very useful during testing.
```
settings.setInDemoMode(true);
```
to enable this intensive scanning mode. Let us know if you have more questions.

**Comment by julianlecalvez** [comment]
Hello, 
Thanks a lot for your answer !
So when I arrived this morning, I received my push ! I don't understand why, because I checked my campaign settings and it should've worked yesterday. 
Anyway, I perfectly receive the push every 10 seconds (as I set it up), and if I put the beacon further, I don't receive the push (I set 1 meter at most). Perfect so far ! 

But, I tried to disable the campaign, and I keep receiving the push. Besides, even if I change the message of the push, I keep receiving the first configured push message. 
Is it a normal behavior? How can I at least be sure that disabling my campaign won't send pushes anymore?

Thank you for your help !

Julian

**Comment by eric-kok-ezeeworld** [comment]
Yes, this is problably the normal behaviour. The SDK is quite aggresive in the caching of data, so it can take a while before it forces an update of the campaign data. (The typical cache time is 1 hour.) Even restarting the app will not clear the cache. You can enforce a renewal of the data by clearing all your app data or, perhaps better, request a timout of the caches from code, by calling 
```
Api.getInstance(context).resetCache();
```
(This still invalidates the cache such that on the next request it is loaded from the server, if needed.)

**Comment by julianlecalvez** [comment]
Ok ! I did it and it seems to work ! 

Thanks a lot !

**Comment by julianlecalvez** [comment]
Hi ! 
I got a new problem trying to implement the Broadcast receiver to handle the beacon detection. 
my configuration is the following : 

AndroidManifest.xml 
```
<receiver android:name="com.test.BeaconBroadcastReceiver">
    <intent-filter>
        <action android:name="com.ezeeworld.b4s.android.sdk.monitor.B4S_NOTIFICATION" />
    </intent-filter>
</receiver>
```

and here is my BeaconBroadcastReceiver class : 

```
package com.test;

import ...

public class BeaconBroadcastReceiver extends BroadcastReceiver {
    public void onReceive(Context context, Intent intent) {
        B4SLog.i("B4S", "Broadcaster called !");
    }
}
```

It works perfectly when I put: *android.provider.Telephony.SMS_RECEIVED*, but it doesn't work when I put: *com.ezeeworld.b4s.android.sdk.monitor.B4S_NOTIFICATION*

I don't know if the receiver doesn't catch it or if nothing arrives to my app, but here is the log for a scan (with a beacon around). 
The beacon linked to my campaign is: B4S:8030:FFFF (I changed the IDs to print it here). 
```
V/B4S     (17121): ScanService: Scanned for 3000ms (in 1500ms intervals) and found beacons: 
V/B4S     (17121): 		B4S:802F:AAAA @ 8.71m
V/B4S     (17121): 		B4S:8030:BBBB @ 4.03m
V/B4S     (17121): 		B4S:802F:CCCC @ 9.67m
V/B4S     (17121): 		B4S:8030:DDDD @ 9.79m
V/B4S     (17121): 		B4S:8030:EEEE @ 10.03m
V/B4S     (17121): 		B4S:8030:FFFF @ 0.20m
V/B4S     (17121): ScanService: Sending B4S observations to com.ezeeworld.b4s.android.sample
V/B4S     (17121): ScanService: Next scan in 2000ms
D/B4S     (17121): InteractionService: Matched interaction camp to B4S:8030:FFFF @ 0.20m: locked!
I/B4S     (17121): RegisterSessionStatus: Update session notification status for beacon B4S:8030:FFFF: O
D/B4S     (17121): /setSessionStatus: Calling /setSessionStatus with sSessionId=e8f15d27-fc7c-4c06-8675-ebe08b1281fa&sInnerName=B4S%3A8030%3AFFFF&sStatus=O&sClientId=XXXXXX&sOS=ANDROID
I/B4S     (17121): InteractionService: Notified internally for interaction match camp with text 'Hello from beacon ok 3' and data '{"action”:”test:\/\/detected”,”alert":"0"}'
I/B4S     (17121): RegisterHitTask: Register hit for beacon B4S:8030:FFFF (at 0.20044123379792586m)
D/B4S     (17121): /hit: Calling /hit with sAckData=&sDeviceUdid=XXXXXX&sDeviceModel=XXXXX+5&sDeviceOs=ANDROID&sOsVersion=5.1.1&sAppVersion=1&nLongitude=2.345634&nLatitude=48.885435&sAppId=XXXX&sCustomerRef=&sClientId=XXXX&sCountry=FRANCE&sGroupId=XXXXX&sShopId=XXXXXX&sBeacon=B4S%3A8030%3AFFFF&sCategoryId=XXXXX&sInteractionId=XXXXX&dDate=2015-06-24T14%3A11%3A34Z&nDistance=0.200441
```

Thank you !

**Comment by eric-kok-ezeeworld** [comment]
By default all campaigns will be matched internally already (as you can see in your log) and will not be broadcasted, so it is normal that you broadcast receiver does not receive any messages.

**Comment by julianlecalvez** [comment]
Thank you!

I am just trying to catch the background detection. I guessed that the above paragraph explains that, isn't it ?

> For custom behaviour, in case none of the normal notification types are used, the SDK sends intent broadcasts to your application when a beacon is matched, such that your application can itself perform an appropriate action like generate the proper notification for the user or start an activity directly.

> As specified above, in the AndroidManifest.xml we define a B4SNotificationReceiver which parses the interaction matches. It should filter on the com.ezeeworld.b4s.android.sdk.monitor.B4S_NOTIFICATION action and extend from BroadcastReceiver directly such that in the onReceive method the broadcasted messages are received as Intents. The same extras are bundled as with normal deep linking.

**Comment by eric-kok-ezeeworld** [comment]
That is correct, but it is only for cases where matches are not matched already internally. Campaigns set up via the B4S Manager currently support enforce one of the internal message types (simple push, rich push, web overlay, etc.), to match the iOS SDK.

**Comment by julianlecalvez** [comment]
Got it ! 
Thank you !
