### ISSUE TITLE
SDK Integration - proguard configuration

### ISSUE THREAD

**Issue by GaelCougnaud** [ezeeworld/B4S-Android-SDK#3]
Hi,

I am trying to integrate your SDK. I would like to know the proguard configuration of your SDK. Indeed, your SDK compile fine in debug, but not in release. Our project activate proguard in release mode. So I need to configure the proguard's project to keep the necessary elements of your SDK and third libraries.

Best regards,
Gaël

**Comment by eric-kok-ezeeworld** [comment]
Hi Gaël,

We currently are not 100% compatible with proguard to obfuscate the code. We are actively working towards this, also to decrease the total size of the library, but at the moment you will need to disable proguard for B4S. The individual dependencies do support proguard already, and their rules can be found in their own repos.

Regards,
Eric

**Comment by GaelCougnaud** [comment]
Hi,

For my part, I have tried to proguard your SDK and others dependencies. This compiles , but it causes a crash.

Gaël

**Comment by eric-kok-ezeeworld** [comment]
I have not tried to build a full Proguard setup, but you need at least the Proguard rules for our dependencies: 
[EventBus](https://github.com/krschultz/android-proguard-snippets/blob/master/libraries/proguard-eventbus.pro)
[Jackson](https://github.com/krschultz/android-proguard-snippets/blob/master/libraries/proguard-jackson-2.pro)
[Retrofit](https://github.com/krschultz/android-proguard-snippets/blob/master/libraries/proguard-square-retrofit2.pro)

They can be found here: https://github.com/krschultz/android-proguard-snippets/tree/master/libraries

For B4S you may exclude it for now. I belief this works something like:
```
-keep class com.ezeeworld.b4s.android.sdk.**
```

**Comment by eric-kok-ezeeworld** [comment]
We have added Proguard support in our development version, such that the next release will allow the use of Proguard (via `minifyEnabled true`) to obfuscate code. The Proguard rules will be shipped in the .aar package, so no additional configuration is required.

If you would like to use Proguard with the 1.8.0 release, please try adding the following configuration in your existing proguard-rules.pro file (or put in a separate file to reference): [proguard.txt](https://github.com/ezeeworld/B4S-Android-SDK/files/100946/proguard.txt). This includes rules for the dependency libraries such as Retrofit.

**Comment by GaelCougnaud** [comment]
Thanks.
