### ISSUE TITLE
Configuration with Retrofit 1.9

### ISSUE THREAD

**Issue by khrisGo** [ezeeworld/B4S-Android-SDK#5]
Hi, 
I want to add the B4S Gradle dependency to my project.
However my project is set with Retrofit 1.9 instead of 2.0.0-beta2.
It generated an exception : java.lang.NoClassDefFoundError: retrofit.Retrofit$Builder

My question is, is it possible to use your SDK with retrofit 1.9?
If so, what must be configured?

Thank you by advance
Best regards

**Comment by erickok** [comment]
You may use both Retrofit 1.x and 2.x simultaneously, as they have unique package and artifact names.

**Comment by khrisGo** [comment]
The packages are not exactly the same.
Here are some Gradle errors I get when I try to use 1.9 & 2.0.0-beta2 simultaneously : 

Error:(45, 16) error: cannot find symbol class RetrofitError
Error:(46, 23) error: package retrofit.client does not exist
Error:(39, 16) error: cannot find symbol class RestAdapter
Error:(40, 23) error: package retrofit.client does not exist
Error:(41, 26) error: package retrofit.converter does not exist

**Comment by eric-kok-ezeeworld** [comment]
This is correct, for B4S SDK 1.7.x, which has a dependency on Retrofit 2.0-beta2. Our SDK 1.8, to be release at the latest at the end of this week, has a dependency on Retrofit 2.0-beta3 such that it may be used together with Retrofit 1.9.

**Comment by khrisGo** [comment]
Thank you for the release :) 
However the Gradle installation documentation is out of date about the dependencies to include.
Do you you have an Android documentation like the one about IOS?
Best regards

**Comment by eric-kok-ezeeworld** [comment]
We updated the documentation. What is out of date, according to you?

The migration doc is at https://github.com/ezeeworld/B4S-Android-SDK/wiki/Migration-guide
The full guide (with dependencies listed) is at https://github.com/ezeeworld/B4S-Android-SDK/wiki/Installation-with-Gradle

**Comment by khrisGo** [comment]
Thank you for your answer.
Actually I missread the documentation, you updated the dependencies however, the package name of Retrofit is not the right one.

The following dependencies are written :
compile 'com.squareup.retrofit:retrofit:2.0.0-beta3'
compile 'com.squareup.retrofit:converter-jackson:2.0.0-beta3'


But the package name is com.squareup.retrofit2 making the Retrofit dependencies looks like :
compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
compile 'com.squareup.retrofit2:converter-jackson:2.0.0-beta3'

Best regards

**Comment by eric-kok-ezeeworld** [comment]
You are right, thank you. I corrected the dependencies in to documentation.
