### ISSUE TITLE
Battery consumption when Bluetooth is disabled

### ISSUE THREAD

**Issue by GaelCougnaud** [ezeeworld/B4S-Android-SDK#6]
Hi,

Since I have integrated B4S SDK in our application, my phone informs me that my app consumes too much energy, even if Bluetooth is disabled.
In app log, I have noticed that the ScanService is always turned on. This log happens repeatedly when Bluetooth is disabled : "E/B4S: ScanService: Bluetooth is not enabled by the user: NO scanning can be performed right now (will try again next time)".
Is it possible to modify your SDK to turn off your service when the Bluetooth is not enabled ?
I think you can relaunch it when Bluetooth become enabled with a receiver on Bluetooth state changed event.

Best regards,
Gaël

**Comment by eric-kok-ezeeworld** [comment]
Thanks for the report. Indeed the ScanService keeps active while Bluetooth is deactivated, to respond as soon as possible to changes in BT status. Using the Bluetooth state broadcasts to optimize this process is a smart optimization that we will certainly look into. However, even in the current implementation there is no effective Bluetooth querying and other parts of the SDK would still need to be effective, so the optimizations will be somewhat limited. Certainly we will keep improving battery efficiency overall.

**Comment by kris92** [comment]
Our next release 2.0.1 (scheduled on Jul, 21) will improve battery consumption whatever bluetooth is enabled or disabled.
